alias nv=nvim
alias ls='eza --icons'
alias la='eza -a --icons'
alias lt='eza --icons --tree'
alias ll='eza -lg --icons --time-style=long-iso'
alias lla='eza -alg --icons --time-style=long-iso'
alias lal='eza -alg --icons --time-style=long-iso'
alias ..='cd ../'
alias ...='cd ../../'
alias sl='ls'
alias gpp='g++'
alias grep='rg'
alias du='dust'
alias top='btm'
alias df='duf'
alias ps='procs'
alias disk='diskonaut'
alias euc='cocot -t UTF-8 -p EUC-JP --'
alias sjis='cocot -t UTF-8 -p SJIS --'
alias urxvt='~/bin/run_urxvt'
