alias nv=nvim
alias ls='exa --icons'
alias la='exa -a --icons'
alias lt='exa --icons --tree'
alias ll='exa -lg --icons --time-style=long-iso'
alias lla='exa -alg --icons --time-style=long-iso'
alias lal='exa -alg --icons --time-style=long-iso'
alias ..='cd ../'
alias ...='cd ../../'
alias sl='ls'
alias gpp='g++'
alias grep='rg'
alias du='dust'
alias top='btm'
alias df='duf'
alias ps='procs'
alias disk='diskonaut'
alias euc='cocot -t UTF-8 -p EUC-JP --'
alias sjis='cocot -t UTF-8 -p SJIS --'
alias urxvt='~/bin/run_urxvt'
